server:
  port: 8064
  
spring:
  application:
    name: API_GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: BOOKSERVICE
        uri: lb://BOOKSERVICE
        predicates:
        - Path=/books/**

      - id: USERSERVICE
        uri: lb://USERSERVICE
        predicates:
        - Path=/users/**        